### PR TITLE
Crash on Network Exception #7

### LINKED ISSUE #7: Crash on Network Exception
The app only handles API errors (the app successfully connected to the API server and received a response but the status is not 0). Scenarios where the app did not successfully reach the server, lead to a crash.

Below is the list of common error scenarios that leads to a crash but should be handled by the app gracefully. Note that this list is not exhaustive.
1. No internet connection
2. Invalid URLs/endpoints such as changing `AppTrainingLoginError.htm` to `NewLogin.htm`
3. The connection has timed out.

### Bonus
The handling for these crashes should be easily reusable for all existing API calls as well as for new APIs in the future.

### PR DESCRIPTION
**Pull request by davidimbong**
## What's in this PR

- Closes #7 

- Added exception handling for network errors

## How Has This Been Tested?

- Added a network limit in the emulator to simulate slow internet connection.
- Turned on airplane mode in the emulator to simulate no internet connection

### CODE REVIEW

File: app/src/main/java/com/example/hris/repository/HrisRepository.kt [hunk 1]
```diff
@@ -15,18 +17,40 @@ class HrisRepository @Inject constructor(
...
+//        )
+//
+//        if (call.isSuccess) {
+//            withContext(Dispatchers.IO) {
+//                hrisDao.updateProfile(call.user!!)
+//            }
+//        }
+//        return call
+
+
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/repository/HrisRepository.kt]: Delete block.

File: app/src/main/java/com/example/hris/repository/HrisRepository.kt [hunk 2]
```diff
@@ -36,63 +60,95 @@ class HrisRepository @Inject constructor(
...
+//    suspend fun refreshTimeLogs(): TimeLogsModel =
+//        withContext(Dispatchers.IO) {
+//            val call = HrisApi.retrofitService.getTimeLogs(
+//                userData.value!!.userID
+//            )
+//            if (call.isSuccess) {
+//                hrisDao.updateTimeLogs(call.timeLogs!!)
+//            }
+//            call
+//        }
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/repository/HrisRepository.kt]: Delete block.

File: app/src/main/java/com/example/hris/repository/HrisRepository.kt [hunk 3]
```diff
@@ -36,63 +60,95 @@ class HrisRepository @Inject constructor(
...
 
-    suspend fun refreshLeaves(): LeavesModel =
+
+//    suspend fun addTimeLogs(type: String): ResponseModel =
+//        withContext(Dispatchers.IO) {
+//            HrisApi.retrofitService.addTimeLogs(
+//                userData.value!!.userID,
+//                type
+//            )
+//        }
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/repository/HrisRepository.kt]: Delete block.

File: app/src/main/java/com/example/hris/ui/viewmodels/LoginViewModel.kt [hunk 4]
```diff
@@ -26,22 +27,37 @@ class LoginViewModel @Inject constructor(
...
+//            }
+//            loadingDialogState.value = false
+//            } catch (networkError: IOException) {
+//                message.value = context.getString(R.string.network_error)
+//                loadingDialogState.value = false
+//            }
+//            catch (networkError: TimeoutException){
+//                message.value = context.getString(R.string.timeout_error)
+//                loadingDialogState.value = false
+//            }
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/ui/viewmodels/LoginViewModel.kt]: Delete block.

File: app/src/main/java/com/example/hris/ui/viewmodels/leaves/FileLeaveViewModel.kt [hunk 5]
```diff
@@ -20,23 +22,27 @@ class FileLeaveViewModel @Inject constructor(
     val isSuccess = MutableLiveData<Unit>()
     var type = ""
 
-    fun fileLeave(time: Int, dateFrom: String?, dateTo: String?) {
+    fun fileLeave(time: Int, dateFrom: String?, dateTo: String?, context: Context) {
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/ui/viewmodels/leaves/FileLeaveViewModel.kt]: Remove `context`.

File: app/src/main/java/com/example/hris/ui/viewmodels/leaves/LeavesViewModel.kt [hunk 6]
```diff
@@ -43,17 +45,21 @@ class LeavesViewModel @Inject constructor(
         }
     }
 
-    fun callLeaves() {
+    fun callLeaves(context: Context) {
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/ui/viewmodels/leaves/LeavesViewModel.kt]: Remove `context`

File: app/src/main/java/com/example/hris/ui/viewmodels/timelogs/AddTimeLogsViewModel.kt [hunk 7]
```diff
@@ -20,18 +22,21 @@ class AddTimeLogsViewModel @Inject constructor(
     val liveDataSuccess = MutableLiveData<Unit>()
     val message = MutableLiveData<String>()
 
-    fun addTimeLogs(type: String) {
+    fun addTimeLogs(type: String, context: Context) {
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/ui/viewmodels/timelogs/AddTimeLogsViewModel.kt]: Remove `context`

File: app/src/main/java/com/example/hris/ui/viewmodels/timelogs/TimeLogsViewModel.kt [hunk 8]
```diff
@@ -21,15 +23,19 @@ class TimeLogsViewModel @Inject constructor(
     val loadingDialogState = MutableLiveData<Boolean>()
     val message = MutableLiveData<String>()
 
-    fun callTimeLogs() {
+    fun callTimeLogs(context: Context) {
```
Comment (sherwincatli) [inline app/src/main/java/com/example/hris/ui/viewmodels/timelogs/TimeLogsViewModel.kt]: Remove `context`

**Review by sherwincatli — DISMISSED** [review]

**Review by sherwincatli — APPROVED** [review]
